spring.application.name=demo

# PostgreSQL connection configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/numerology_db
spring.datasource.username=developer
spring.datasource.password=dev_pass

# Hibernate will not create/alter tables - they will be handled manually
spring.jpa.hibernate.ddl-auto=none

# PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Allows scripts to be run only afther the connection is established
spring.jpa.defer-datasource-initialization=true

# Prints all SQL queries in console (for debug purposes only)
spring.jpa.show-sql=true

# Fully deactivates any automated SQL initialization (avoids schema.sql or data.sql to be ran at startup)
spring.sql.init.mode=never