spring.application.name=demo

# db connection
spring.datasource.url=jdbc:postgresql://localhost:5432/numerology_db
spring.datasource.username=developer
spring.datasource.password=dev_pass

# automatic table creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# initialize data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# SQL print in console (for debug purposes only)
spring.jpa.show-sql=true